package main.client.config;

import java.util.HashMap;
import java.util.Map;

public class Strings {
    public static final String SIGN_IN = "Sign in";
    public static final String WELCOME_TO_INVOICING = "Welcome to Invoicing!";
    public static final String WRITE_YOUR_EMAIL = "Write your email:";
    public static final String WRITE_YOUR_PASSWORD = "Write your password:";
    public static final String SUCCESS = "Success";
    public static final String EMPTY_STRING = "";
    public static final String MAIN_MENU = "Main menu";
    public static final String TITLE = "Title: ";
    public static final String MESSAGE = "Message: ";
    public static final String ERROR = "Error: ";
    public static final String TOKEN = "TOKEN";
    public static final String MESSAGE_KEY = "MESSAGE";
    public static final String ERROR_KEY = "ERROR";
    public static final String CHOOSE_FROM_THE_FOLLOWING_OPTIONS = "Choose from the following options: ";
    public static final String VIEW_CLIENTS_1 = "1) View Clients";
    public static final String LOGOUT_2 = "2) Logout";
    public static final String UNKNOWN_OPTION_WAS_CHOSEN = "Unknown option was chosen.";
    public static final String CLIENTS = "Clients";
    public static final String TABLE = "TABLE";
    public static final String NUMBER_OF_CLIENTS_THAT_YOU_HAVE ="Number of clients that you have: ";
    public static final String CLIENTS_INFORMATION = "Clients information";
    public static final String FIRST_NAME = "First name";
    public static final String LAST_NAME = "Last name";
    public static final String EMAIL = "Email";
    public static final String ORGANIZATION = "Organization";
    public static final String INVOICED_AMOUNT = "Invoiced amount (EUR)";
    public static final String RECEIVED_AMOUNT = "Received amount (EUR)";
    public static final String ADD_CLIENT_1 = "1) Add client";
    public static final String DELETE_CLIENT_2 = "2) Delete client";
    public static final String GO_BACK_3 = "3) Go back";
    public static final String ONE = "1";
    public static final String TWO = "2";
    public static final String THREE = "3";
    public static final String NEW_CLIENT = "New client";
    public static final String WRITE_CLIENTS_FIRST_NAME = "Write clients' first name:";
    public static final String WRITE_CLIENTS_LAST_NAME = "Write clients' last name:";
    public static final String WRITE_CLIENTS_ORGANIZATION = "Write clients' organization:";
    public static final String WRITE_CLIENTS_EMAIL = "Write clients' email:";
    public static final String DELETE_CLIENT = "Delete client";
    public static final String CHOOSE_CLIENT_TO_DELETE = "Choose client to delete:";
    public static final String ARE_YOU_SURE = "Are you sure";
    public static final String ARE_YOU_SURE_ = "Are you sure?";
    public static final String YES = "Yes";
    public static final String NO = "No";
    public static final String Y = "y";
    public static final String N = "n";
    public static final String SUCCESS_CLIENT_WAS_NOT_DELETED = "Success: Client was not deleted";
    //    public static final String ;
}
